export const formatUnidade = (key) => {
    const unidadeMap = {
        'ea carlos heins funke':'EA Carlos Heins Funke',
        'biblioteca publica':'Biblioteca Publica',
        'sede':'Sede',
        'sed nucleo de gestao de pessoas':'SED - Núcleo de Gestão de Pessoas',
        'gerencia de administracao e financas':'Gerência de Administração e Finanças',
        'educacao profissional centro xv':'Educação Profissional Centro XV',
        'em dr nelson de miranda coutinho':'EM Dr. Nelson de Miranda Coutinho',
        'gerencia de infraestrutura':'Gerência de Infraestrutura',
        'cei prof iraci schmidlin':'Cei Prof Iraci Schmidlin',
        'almoxarifado':'Almoxarifado',
        'em prof laura andrade':'EM Prof Laura Andrade',
        'em prof edgar m castanheira':'EM Prof Edgar M Castanheira',
        'em joao costa':'EM Joao Costa',
        'gerencia de educacao basica sede':'Gerência de Educação Básica - Sede',
        'em sen carlos g de oliveira':'EM Sen Carlos G De Oliveira',
        'em pref nilson wilson bender':'EM Pref Nilson Wilson Bender',
        'em pref geraldo wetzel':'EM Pref Geraldo Wetzel',
        'em prof virginia soares':'EM Prof Virginia Soares',
        'em dr abdon batista':'EM Dr Abdon Batista',
        'em dr ruben roberto schmidlin':'EM Dr Ruben Roberto Schmidlin',
        'educacao profissional textil':'Educação Profissional Textil',
        'em enf hilda anna krisch':'EM Enf. Hilda Anna Krisch',
        'em pres castello branco':'EM Pres Castello Branco',
        'em padre valente simioni':'EM Padre Valente Simioni',
        'em prof elizabeth von dreifuss':'EM Prof Elizabeth Von Dreifuss',
        'em pref wittich freitag':'EM Pref Wittich Freitag',
        'em lauro carneiro de loyola':'EM Lauro Carneiro De Loyola',
        'gerencia de tecnologias educacionais':'Gerência de Tecnologias Educacionais',
        'educacao profissional cespi':'Educação Profissional CESPI',
        'em nove de marco':'EM Nove De Marco',
        'em karin barkemeyer':'Em Karin Barkemeyer',
        'cei jose francisco vieira':'Cei José Francisco Vieira',
        'em prof oswaldo cabral':'EM Prof Oswaldo Cabral',
        'em dr sadalla amin ghanem':'EM Dr Sadalla Amin Ghanem',
        'caic prof mariano costa':'Caic Prof Mariano Costa',
        'em prof ada s da silveira':'EM Prof Ada S Da Silveira',
        'em prof eladir skibinski':'EM Prof Eladir Skibinski',
        'em hans dieter schimidt':'EM Hans Dieter Schimidt',
        'em prof saul santanna o dias':'EM Prof Saul Santanna O Dias',
        'em prof lacy luiza da c flores':'EM Prof Lacy Luiza Da C Flores',
        'escola municipal de jovens e adultos':'Escola Municipal de Jovens e Adultos',
        'cei doce infancia':'Cei Doce Infância',
        'cei sigelfrid poffo':'Cei Sigelfrid Poffo',
        'em prof zulma do r miranda':'EM Prof Zulma Do R Miranda',
        'em prof anna maria harger':'EM Prof Anna Maria Harger',
        'cei salete konecki':'CEI Salete Konecki',
        'cei espaco da crianca':'Cei Espaço da Criança',
        'caic francisco j r de oliveira':'Caic Francisco J R De Oliveira',
        'cartorio':'CARTÓRIO',
        'em jose antonio navarro lins':'EM Jose Antonio Navarro Lins',
        'em ver curt alvino monich':'EM Ver. Curt Alvino Monich',
        'cei silvia regina cavalheiro':'CEI Silvia Regina Cavalheiro',
        'em placido xavier vieira':'EM Plácido Xavier Vieira',
        'em prof avelino marcante':'EM Prof Avelino Marcante',
        'em prof joao bernardino da s j':'EM Prof Joao Bernardino Da S J',
        'em prof rosa maria berezoski':'EM Prof Rosa Maria Berezoski',
        'em ver arinor vogelsanger':'EM Ver. Arinor Vogelsanger',
        'em paul harris':'EM Paul Harris',
        'em pref baltasar buschle':'EM Pref Baltasar Buschle',
        'em gov pedro ivo campos':'EM Gov. Pedro Ivo Campos',
        'cei zilda arns neumann':'CEI Zilda Arns Neumann',
        'educacao profissional casa brasil sul':'Educação Profissional Casa Brasil Sul',
        'em prof aluizius sehnem':'EM Prof Aluizius Sehnem',
        'em prof orestes guimaraes':'EM Prof Orestes Guimaraes',
        'cei pedro ivo':'Cei Pedro Ivo',
        'em pref max colin':'EM Pref. Max Colin',
        'em anita garibaldi':'EM Anita Garibaldi',
        'em emilio paulo r hardt':'EM Emilio Paulo R Hardt',
        'em dom jaime de barros camara':'EM Dom Jaime De Barros Camara',
        'a disposicao sindicato dos servidores':'A Disposição - Sindicato dos Servidores',
        'em prefeito luiz gomes':'EM Prefeito Luiz Gomes',
        'em anaburgo':'EM Anaburgo',
        'em pauline parucker':'EM Pauline Parucker',
        'em pres arthur costa e silva':'EM Pres Arthur Costa E Silva',
        'em joao de oliveira':'EM Joao De Oliveira',
        'em prof bernardo tank':'EM Prof Bernardo Tank',
        'educacao profissional cesita':'Educação Profissional CESITA',
        'em gov heriberto hulse':'EM Gov. Heriberto Hulse',
        'em adolfo bartsch':'EM Adolfo Bartsch',
        'em prof sylvio sniecikovski':'EM Prof Sylvio Sniecikovski',
        'em pref joaquim felix moreira':'EM Pref Joaquim Felix Moreira',
        'polo':'POLO',
        'em monsenhor sebastiao scarzello':'EM Monsenhor Sebastião Scarzello',
        'em dr amador aguiar':'EM Dr Amador Aguiar',
        'educacao profissional casa brasil norte':'Educação Profissional Casa Brasil Norte',
        'em valentin joao da rocha':'EM Valentin Joao Da Rocha',
        'gerencia de assistencia ao educando sede':'Gerência de Assistência ao Educando - Sede',
        'em prof thereza mazzolli hreisem':'EM Prof Thereza Mazzolli Hreisem',
        'em pastor hans muller':'EM Pastor Hans Muller',
        'escola municipal portaria 028gab':'Escola Municipal - Portaria 028/GAB',
        'escola municipal portaria 072 avelino extensao':'Escola Municipal Portaria 072 (Avelino -Extensão)',
        'em prof maria regina leal':'EM Prof Maria Regina Leal',
        'em prof honorio saldo':'EM Prof Honorio Saldo',
        'em portaria 1275 karin extensao':'EM Portaria 1275 (Karin -Extensão)',
        'cei marilene dos passos santos':'Cei Marilene dos Passos Santos',
        'cei aventuras de crianca':'Cei Aventuras de Criança',
        'cei odorico fortunato':'Cei Odorico Fortunato',
        'cei alegria de viver':'Cei Alegria de Viver',
        'cei luiza maria veiga':'Cei Luiza Maria Veiga',
        'cei ademar garcia':'Cei Ademar Garcia',
        'cei branca de neve':'Cei Branca De Neve',
        'cei meu pequeno mundo':'Cei Meu Pequeno Mundo',
        'cei parque guarani':'Cei Parque Guarani',
        'cei ponte serrada':'Cei Ponte Serrada',
        'cei namir alfredo zattar':'Cei Namir Alfredo Zattar',
        'cei espinheiros':'Cei Espinheiros',
        'cei prof juliana de c vieira':'Cei Prof Juliana de C. Vieira',
        'em hermann muller':'EM Hermann Muller',
        'em sete de setembro':'EM Sete De Setembro',
        'cei fatima':'Cei Fatima',
        'em prof reinaldo de franca':'EM Prof Reinaldo De Franca',
        'cei raio de sol':'Cei Raio De Sol',
        'em eugenio klug':'EM Eugenio Klug',
        'cei prof miraci dereti':'Cei Prof. Miraci Dereti',
        'cei dep pedro p h colin':'Cei Dep. Pedro P. H. Colin',
        'em otto ristow filho':'EM Otto Ristow Filho',
        'em padre carlos':'EM Padre Carlos',
        'cei estrelinha brilhante':'Cei Estrelinha Brilhante',
        'cei esperanca':'Cei Esperança',
        'cei prof herondina da s vieira':'Cei Prof. Herondina da S. Vieira',
        'cei justina rosa fachini':'CEI Justina Rosa Fachini',
        'cei miosotis':'Cei Miosotis',
        'cei celio gomes de oliveira':'Cei Celio Gomes De Oliveira',
        'cei pao de mel':'Cei Pão de Mel',
        'cei adolfo artmann':'Cei Adolfo Artmann',
        'em jose do patrocinio':'EM Jose Do Patrocinio',
        'cei beija flor':'Cei Beija Flor',
        'em pref emilio stock jr':'EM Pref Emilio Stock Jr',
        'em prof alfonso fiedler':'EM Prof Alfonso Fiedler',
        'cei mundo azul':'Cei Mundo Azul',
        'cei lirio do campo':'Cei Lirio Do Campo',
        'em fritz benkendorf':'EM Fritz Benkendorf',
        'cei pequena sereia':'Cei Pequena Sereia',
        'em prof senhorinha soares':'EM Prof Senhorinha Soares',
        'em prof jose mota pires':'EM Prof Jose Mota Pires',
        'cei girassol':'Cei Girassol',
        'em prof isabel silveira machado':'EM Prof Isabel Silveira Machado',
        'e r prof waleska may engelmann':'E. R. Prof Waleska May Engelmann',
        'cei arte e vida':'Cei Arte e Vida',
        'cei castelo branco':'Cei Castelo Branco',
        'cei morro do meio':'Cei Morro Do Meio',
        'cei amandos finder':'Cei Amandos Finder',
        'cei antonio bruhmuller':'CEI Antônio Bruhmuller',
        'cei ivan rodrigues':'Cei Ivan Rodrigues',
        'cei pequeno principe':'Cei Pequeno Principe',
        'cei azelir t pacheco':'Cei Azelir T. Pacheco',
        'cei maria laura cardoso eleoterio':'CEI Maria Laura Cardoso Eleotério',
        'cei pedacinho do ceu':'Cei Pedacinho Do Ceu',
        'cei jardim sofia':'Cei Jardim Sofia',
        'cei jorge luiz vanderwegen':'Cei Jorge Luiz Vanderwegen',
        'cei teresa campregher moreira':'CEI Teresa Campregher Moreira',
        'cei bemmequer':'Cei Bem-Me-Quer',
        'cei abdon da silveira':'CEI Abdon da Silveira',
        'cei itaum':'Cei Itaum',
        'cei cachinhos de ouro':'Cei Cachinhos De Ouro',
        'cei sol nascente':'Cei Sol Nascente',
        'cei espaco encantado':'Cei Espaço Encantado',
        'cei juarez machado':'Cei Juarez Machado',
        'cei eliane kruger':'Cei Eliane Kruger',
        'cei bianca carolina pinheiro':'CEI Bianca Carolina Pinheiro',
        'cei ciranda cirandinha':'Cei Ciranda Cirandinha',
        'cei prof felicia cardoso vieira':'CEI Prof Felícia Cardoso Vieira',
        'cei monteiro lobato':'CEI Monteiro Lobato',
        'cei gustavo zietz':'Cei Gustavo Zietz',
        'cei portaria 1276 cachinhos extensao':'CEI Portaria 1276 (Cachinhos - Extensão)',
        'cei prof debora cristina neves da silva ruiz paloma':'Cei Prof Débora Cristina Neves da Silva Ruiz Paloma',
        'cei mario avancini':'Cei Mario Avancini',
        'educacao profissional casa brasil nordeste':'Educação Profissional Casa Brasil Nordeste',
        'em prof francisco rieper':'EM Prof Francisco Rieper',
        'e r germano lenschow':'E. R. Germano Lenschow',
        'em cel alire carneiro':'EM Cel Alire Carneiro',
        'em alfredo g henrique':'EM Alfredo G. Henrique',
        'em prof julio machado da luz':'EM Prof Julio Machado Da Luz',
        'e r prof maria madalena mazzoli':'E. R. Prof Maria Madalena Mazzoli',
        'em ver hubert hubener':'EM Ver. Hubert Hubener',
        'e r evaldo koehler':'E. R. Evaldo Koehler',
        'escola municipal portaria 092 nilson bender extensao':'Escola Municipal Portaria 092 (Nilson Bender - Extensão)',
        'e r prof joao meerholz':'E. R. Prof Joao Meerholz',
        'em hans muller':'Em Hans Muller',
        'cei botaozinho de rosa':'Cei Botaozinho De Rosa',
        'cei paraiso da crianca':'Cei Paraiso Da Crianca',
        'cei sonho de crianca':'Cei Sonho de Criança',
        'cei peter pan':'Cei Peter Pan',
        'cei ze carioca':'Cei Ze Carioca',
        'cei sementinha':'Cei Sementinha',
        'a disposicao associacao servidores':'A Disposição - Associação Servidores',
        'ama':'AMA',
        'apiscae':'APISCAE',
        'a disposicao fundacao cultural':'A Disposição - Fundação Cultural',
        'ajidevi':'AJIDEVI',
        'a disposicao sede':'A Disposição - SEDE',
        'a disposicao secretaria da saude':'A Disposição - Secretaria da Saúde',
        'a disposicao fundacao cultural':'A Disposição - Fundação Cultural',
        'cei professora zelandia thomazi bratti':'Cei Professora Zelândia Thomazi Bratti',
        'cei prof herondina da silva vieira':'Cei Prof Herondina da Silva Vieira',
        'escola municipal portaria 028gab castelo branco extensao':'Escola Municipal - Portaria 028/GAB - (Castelo Branco Extensão)',
        'ensino regular':'Ensino Regular',
        'sed sede':'SED - Sede',
        'sed gerencia de assistencia ao educando sede':'SED - Gerência de Assistência ao Educando - Sede',
        'sed almoxarifado':'SED - Almoxarifado',
        'sed gerencia de educacao basica sede':'SED - Gerência de Educação Básica - Sede',
        'sed polo':'SED - POLO',
        'sed ajidevi':'SED - AJIDEVI',
        'sed ama':'SED - AMA',
        'sed apae':'SED - APAE',
        'sed apiscae':'SED - APISCAE',
        'sed cartorio':'SED - CARTÓRIO',
        'sed a disposicao sede':'SED - A Disposição - SEDE',
        'sed a disposicao associacao servidores':'SED - A Disposição - Associação Servidores',
        'sed a disposicao fundacao cultural':'SED - A Disposição - Fundação Cultural',
        'sed a disposicao secretaria da saude':'SED - A Disposição - Secretaria da Saúde',
        'sed a disposicao sindicato dos servidores':'SED - A Disposição - Sindicato dos Servidores',
        'sed a disposicao fundacao cultural':'SED - A Disposição - Fundação Cultural',
        'sed gerencia de infraestrutura':'SED - Gerência de Infraestrutura',
        'sed gerencia de administracao e financas':'SED - Gerência de Administração e Finanças',
        'sed educacao profissional textil':'SED - Educação Profissional Textil',
        'sed educacao profissional cesita':'SED - Educação Profissional CESITA',
        'sed educacao profissional centro xv':'SED - Educação Profissional Centro XV',
        'sed educacao profissional cespi':'SED - Educação Profissional CESPI',
        'sed educacao profissional casa brasil sul':'SED - Educação Profissional Casa Brasil Sul',
        'sed educacao profissional casa brasil norte':'SED - Educação Profissional Casa Brasil Norte',
        'sed educacao profissional casa brasil nordeste':'SED - Educação Profissional Casa Brasil Nordeste',
        'sed gerencia de tecnologias educacionais':'SED - Gerência de Tecnologias Educacionais',
        'em gov heriberto hulse':'Em Gov Heriberto Hulse',
        'ss area de patrimonio':'SS - Área de Patrimônio',
        'area de apoio gabinete':'Area de Apoio Gabinete',
        'em anna maria harger':'Em Anna Maria Harger',
        'em prof ada santana silveir':'Em Prof Ada Santana Silveir',
        'em carlos gomes de oliveira':'Em Carlos Gomes De Oliveira',
        'em portaria 028 castello branco extensao':'EM Portaria 028 (Castello Branco - Extensão)',
        'em professora rosangela martinowsky baptista':'EM Professora Rosangela Martinowsky Baptista',
        'sgp uss unidade saude servidor':'SGP - USS - Unidade Saude Servidor'
    };
    if (!key) return '';
    return unidadeMap[key] || key;
}